name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: read 
jobs:
  release:
    permissions: write-all
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm ci && npm run build
      - name: Release
        script:
          - export GH_TOKEN=${{ secrets.NPM_TOKEN }}
          - export NPM_TOKEN=${{ secrets.NPM_TOKEN }}
          - export CI=true
          - export HUSKY_SKIP_HOOKS=1
          - npm run build
          - npx semantic-release
        # env:
        #   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        #   GITHUB_TOKEN: ${{ secrets.AUTO_RELEASE_TOKEN }}
        # run: npx semantic-release