name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: read 
jobs:
  release:
    permissions: write-all
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm ci && npm run build
      - name: setup git config
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git config user.name "Essence Autorelease Bot"
          git config user.email "<>"
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn release && git push --follow-tags
      - name: Get Package Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: package.json
      - name: Publish Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: gh release create v${{ steps.package-version.outputs.current-version}}

